{
	"id": "CVE-2020-13596",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
	"poc": {
		"references": [
			"https://www.oracle.com/security-alerts/cpujan2021.html"
		],
		"githubs": [
			"https://github.com/ARPSyndicate/cvemon",
			"https://github.com/Live-Hack-CVE/CVE-2020-13596",
			"https://github.com/Qubo-FNSD/Mapl-App-NVDs"
		]
	}
}
