{
  "id": "CVE-2020-29651",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
  "poc": {
    "references": [
      "https://www.oracle.com/security-alerts/cpujul2022.html"
    ],
    "githubs": [
      "https://github.com/Live-Hack-CVE/CVE-2020-29651",
      "https://github.com/engn33r/awesome-redos-security",
      "https://github.com/mirac7/GraphYourCodeVulnerability",
      "https://github.com/yetingli/PoCs"
    ]
  }
}
