{
  "id": "CVE-2022-35997",
  "tags": [
    {
      "label": "Product",
      "message": "tensorflow"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "CWE-617: Reachable Assertion"
    }
  ],
  "description": " TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
  "poc": {
    "githubs": [
      "https://github.com/ARPSyndicate/cvemon",
      "https://github.com/skipfuzz/skipfuzz"
    ]
  }
}
