{
	"id": "CVE-2021-25287",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.",
	"poc": {
		"references": [
			"https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470"
		]
	}
}
